[package]
name = "msh"
version = "0.1.0"
edition = "2024"

[dependencies]
baby_shark = "0.3.12"
clap = { version = "4.5.49", features = ["derive"] }
gltf = "1.4.1"
kiss3d = { version = "0.36.0", features = ["vertex_index_u32"] }
